kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment
  namespace: myskincare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment
    spec:
      imagePullSecrets:
        - name: quay-secret-registry
      containers:
        - name: payment
          image: example-registry-quay-openshift-operators.apps.cluster-csvlw.csvlw.sandbox1045.opentlc.com/fajjarnr/payment:latest
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: FRONT_PAGE
              value: frontpage-service
          imagePullPolicy: Always
