apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontpage
  name: frontpage-service
  namespace: myskincare
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontpage
