apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin-service
  namespace: myskincare
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: admin
