version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 572372482934.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...          
      - docker build -t myskincare .
      - docker tag myskincare:latest 572372482934.dkr.ecr.us-east-1.amazonaws.com/myskincare:latest
  
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 572372482934.dkr.ecr.us-east-1.amazonaws.com/myskincare:latest
      - echo Writing image definitions file...
      - printf '[{"name":"Frontpage","imageUri":"572372482934.dkr.ecr.us-east-1.amazonaws.com/myskincare:latest"}]' > imagedefinitions.json


artifacts:
    files: imagedefinitions.json